# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318
        cors:
          allowed_origins:
            - ${FRONTEND_URL_HTTPS}
            - ${FRONTEND_URL_HTTP}
        include_metadata: true


processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${env:HONEYCOMB_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
